add_newline = false
format = """$directory$git_branch$git_state$git_status \
$kubernetes$python$nodejs$character"""

[directory]
truncation_length = 3
style = "fg:#91d7e3"

[character]
success_symbol = "[❯](bold fg:#cba6f7)"
error_symbol   = "[✖](bold fg:#ed8796)"
